# Generated by Django 4.2.17 on 2025-01-25 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
