# Generated by Django 5.0.7 on 2025-06-27 12:30

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=250,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator],
            ),
        ),
    ]
