# Generated by Django 5.0.7 on 2025-06-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0029_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="Permissions",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="users", related_query_name="user", to="auth.permission"
            ),
        ),
    ]
