# Generated by Django 4.2.17 on 2025-01-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("flights", "0005_remove_flight_booking_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passport_name", models.CharField(max_length=100)),
                ("email", models.EmailField(editable=False, max_length=254)),
                ("seats_booked", models.PositiveIntegerField()),
                (
                    "travel_class",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("business", "Business"),
                            ("first_class", "First Class"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credit_card_name", models.CharField(max_length=100)),
                ("credit_card_number", models.CharField(max_length=19)),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="flights.flight",
                    ),
                ),
            ],
        ),
    ]
