# Generated by Django 4.2.17 on 2025-07-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="credit_card_name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="credit_card_number",
        ),
        migrations.AddField(
            model_name="booking",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="nationality",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="passport_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="passport_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
