# Generated by Django 4.2.17 on 2025-07-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0006_flight_flight_number_delete_flightname"),
        ("booking", "0002_remove_booking_credit_card_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="flight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="flights.flight",
            ),
        ),
    ]
