# Generated by Django 4.2.17 on 2025-07-10 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_booking_flight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="passport_expiry_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="passport_name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="passport_number",
        ),
    ]
