# Generated by Django 4.2.17 on 2025-01-10 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0002_flight_arrival_airport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_names",
                        to="flights.flight",
                    ),
                ),
            ],
        ),
    ]
