# Generated by Django 4.2.17 on 2025-01-22 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0004_alter_flightname_flight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="booking_type",
        ),
    ]
