# Generated by Django 4.2.17 on 2025-07-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0005_remove_flight_booking_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="FlightName",
        ),
    ]
